pipeline {
  agent any

  tools {
      nodejs "node25"
  }
  parameters {
    string(name: 'IMAGE_TAG', defaultValue: '', description: 'Image tag from orchestrator')
  }

  environment {
    SONAR_HOME = tool "sonar"

    IMAGE_NAME          = 'claw4321/termistack-frontend'
    DOCKER_REGISTRY_URL = 'https://index.docker.io/v1/'
    TRIVY_SEVERITY      = 'HIGH,CRITICAL'
    TRIVY_EXIT_CODE     = '0'
    SYFT_FORMAT         = "spdx-json"
  }

  stages{
    stage("Checkout"){
      steps {
        git branch: "main", url: "https://github.com/AmulThantharate/TermiStack.git"
      }
    }

    stage("Image Tag"){
      steps{
        script{
          if (params.IMAGE_TAG?.trim()){
            env.IMAGE_TAG = params.IMAGE_TAG
          } else {
            env.IMAGE_TAG = sh(script: 'git log -1 --format="%h"', returnStdout: true).trim()
          }
          echo "USING IMAGE_TAG = ${env.IMAGE_TAG}"
        }
      }
    }

    stage("Install Dependencies") {
      steps {
        dir("frontend"){
          sh '''
            echo "=== Installing Dependencies ==="
            rm -rf node_modules
            npm install --legacy-peer-deps --no-audit
          '''
        }
      }
    }

    stage("Lint") {
      steps {
        dir("frontend"){
          sh '''
            echo "=== Linting ==="
            npm run lint
        '''
        }
      }
    }

    stage("Test") {
      steps {
        dir("frontend"){
          sh '''
            echo "=== Running Tests ==="
            npm run test
          '''
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
          dir("./frontend") {
          withSonarQubeEnv('sonar') {
            sh """
              ${SONAR_HOME}/bin/sonar-scanner \
              -Dsonar.projectName='termistack-frontend' \
              -Dsonar.projectKey='termistack-frontend' \
              -Dsonar.sources=. \
              -Dsonar.exclusions=**/node_modules/**
            """
        }
          }
      }
    }

    stage("Quality Gate"){
      steps{
        timeout(time: 5, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }

    stage("Trivy File System Scan") {
      steps {
        sh "mkdir -p reports/frontend && trivy fs ./frontend --format table -o reports/frontend/trivy-fs-report.html"
      }
      post {
        always {
          publishHTML([
            allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportDir: 'reports/frontend',
            reportFiles: 'trivy-fs-report.html',
            reportName: 'Trivy FS Scan'
          ])
        }
      }
    }

    stage("Docker Build"){
      steps{
        dir("frontend") {
          sh """
            docker build \
            -t ${IMAGE_NAME}:${IMAGE_TAG} \
            -t ${IMAGE_NAME}:latest \
            .
          """
        }
      }
    }

    stage('Security Scans') {
      parallel {

        stage('Trivy Image Scan') {
          steps {
            sh """
              trivy image \
                --severity ${TRIVY_SEVERITY} \
                --exit-code ${TRIVY_EXIT_CODE} \
                ${IMAGE_NAME}:${IMAGE_TAG}
            """
          }
        }

        stage('Syft SBOM') {
          steps {
            sh """
              syft ${IMAGE_NAME}:${IMAGE_TAG} \
              -o ${SYFT_FORMAT} > syft-frontend-sbom.json
            """
            archiveArtifacts artifacts: 'syft-frontend-sbom.json', allowEmptyArchive: true
          }
        }
      }
    }

    stage("Docker Push") {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'DOCKER_CRED',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG
          '''
        }
      }
    }

  }
  post {
    always {
      cleanWs()
    }
  }
}
